version: '3.8'

services:
  stackapi:
    image: stackapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
      - "8001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


